spring.application.name=demo-mcp-java

# Set the default profile to postgres
spring.profiles.active=postgres

---

spring.config.activate.on-profile=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/mcp_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

---

spring.config.activate.on-profile=oracle

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:mcp_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
